JonathanLim46/vetlink-mobile-app

.idea/.gitignore, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/vetlink/Profile.kt, app/src/main/java/com/example/vetlink/activity/LoginActivity.kt, app/src/main/java/com/example/vetlink/activity/MainActivity.kt, app/src/main/java/com/example/vetlink/activity/SecondSplashActivity.kt, app/src/main/java/com/example/vetlink/data/network/AuthApi.kt
implementasi profile fragment untuk logout
=> kevin, features/implment-profile-fragment

app/build.gradle.kts, app/src/main/java/ClinicList.kt, app/src/main/java/ClinicListAdapter.kt, app/src/main/java/com/example/vetlink/Clinic.kt, app/src/main/java/com/example/vetlink/Forum.kt, app/src/main/java/com/example/vetlink/Home.kt, app/src/main/java/com/example/vetlink/activity/LoginActivity.kt, app/src/main/java/com/example/vetlink/activity/MainActivity.kt, app/src/main/java/com/example/vetlink/activity/auth/AuthListener.kt, app/src/main/java/com/example/vetlink/activity/auth/LoginViewModel.kt, app/src/main/java/com/example/vetlink/data/model/user/ProfileResponse.kt, app/src/main/java/com/example/vetlink/data/model/user/User.kt, app/src/main/java/com/example/vetlink/data/network/RetrofitInstance.kt, app/src/main/java/com/example/vetlink/data/network/UserApi.kt, app/src/main/java/com/example/vetlink/util/ViewUtils.kt, gradle.properties
mendapatkan nama user yang login
=> kevin, features/get-customer-name

app/build.gradle.kts, app/src/main/java/com/example/vetlink/activity/MainActivity.kt, app/src/main/java/com/example/vetlink/data/model/auth/LogoutResponse.kt, app/src/main/java/com/example/vetlink/data/network/AuthApi.kt, app/src/main/java/com/example/vetlink/data/network/RetrofitInstance.kt, app/src/main/java/com/example/vetlink/fragment/HomeFragment.kt, app/src/main/java/com/example/vetlink/fragment/ProfileFragment.kt, app/src/main/java/com/example/vetlink/repository/AuthRepository.kt, app/src/main/java/com/example/vetlink/repository/UserRepository.kt, app/src/main/java/com/example/vetlink/viewModel/MainActivityViewModel.kt, app/src/main/java/com/example/vetlink/viewModel/ProfileFragmentViewModel.kt, app/src/main/java/com/example/vetlink/viewModel/ViewModelFactory.kt, gradle/libs.versions.toml
implementasi mvvm untuk login dan logout
=> kevin, features/login-logout-mvvm

app/src/main/java/com/example/vetlink/activity/LoginActivity.kt, app/src/main/java/com/example/vetlink/activity/SignupActivity.kt, app/src/main/java/com/example/vetlink/data/network/AuthApi.kt, app/src/main/java/com/example/vetlink/repository/AuthRepository.kt, app/src/main/java/com/example/vetlink/viewModel/RegisterActivityViewModel.kt, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/values/strings.xml
membuat implementasi untuk fitur registrasi
=> kevin, features/registrasion

app/src/main/java/com/example/vetlink/activity/LoginActivity.kt, app/src/main/java/com/example/vetlink/data/network/AuthApi.kt, app/src/main/java/com/example/vetlink/viewModel/LoginActivityViewModel.kt
error handling ketika credential login salah
=> kevin, bugfix/handling-invalid-credential

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/vetlink/activity/SignupActivity.kt, app/src/main/java/com/example/vetlink/data/network/AuthApi.kt, app/src/main/java/com/example/vetlink/repository/AuthRepository.kt, app/src/main/java/com/example/vetlink/viewModel/RegisterActivityViewModel.kt
implementasi registrasi dengan gambar
=> kevin, features/register-with-profile-picture

.idea/misc.xml, app/src/main/java/com/example/vetlink/activity/MainActivity.kt, app/src/main/java/com/example/vetlink/adapter/ClinicList.kt, app/src/main/java/com/example/vetlink/adapter/ClinicListAdapter.kt, app/src/main/java/com/example/vetlink/adapter/PetsList.kt, app/src/main/java/com/example/vetlink/data/model/veteriner/Veteriner.kt, app/src/main/java/com/example/vetlink/data/model/veteriner/VeterinersResponse.kt, app/src/main/java/com/example/vetlink/data/network/VeterinerApi.kt, app/src/main/java/com/example/vetlink/fragment/ClinicFragment.kt, app/src/main/java/com/example/vetlink/fragment/HomeFragment.kt, app/src/main/java/com/example/vetlink/fragment/MyPetsFragment.kt, app/src/main/java/com/example/vetlink/fragment/PetDetailsFragment.kt, app/src/main/java/com/example/vetlink/repository/AuthRepository.kt, app/src/main/java/com/example/vetlink/repository/VeterinerRepository.kt, app/src/main/java/com/example/vetlink/viewModel/MainActivityViewModel.kt, app/src/main/java/com/example/vetlink/viewModel/ViewModelFactory.kt
implementasi fragment clinic dengan api
=> kevin, features/fragment-clinic-impl

app/src/main/java/com/example/vetlink/activity/MenuActivity.kt, app/src/main/java/com/example/vetlink/adapter/BreedListAdapter.kt, app/src/main/java/com/example/vetlink/adapter/PetTypeListAdapter.kt, app/src/main/java/com/example/vetlink/adapter/PetsCategoryList.kt, app/src/main/java/com/example/vetlink/adapter/PetsList.kt, app/src/main/java/com/example/vetlink/adapter/PetsListAdapter.kt, app/src/main/java/com/example/vetlink/data/model/pets/Pet.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetAddResponse.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetBreed.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetDeleteResponse.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetDetailsResponse.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetType.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetTypeBreedResponse.kt, app/src/main/java/com/example/vetlink/data/network/PetApi.kt, app/src/main/java/com/example/vetlink/data/network/RetrofitInstance.kt, app/src/main/java/com/example/vetlink/fragment/MyPetsFragment.kt, app/src/main/java/com/example/vetlink/fragment/PetDetailsFragment.kt, app/src/main/java/com/example/vetlink/repository/PetRepository.kt, app/src/main/java/com/example/vetlink/viewModel/MenuActivityViewModel.kt, app/src/main/res/drawable/button_selector.xml, app/src/main/res/values/colors.xml
implementasi fitur hapus untuk hewan peliharaan
=> kevin, features/delete-pet

app/src/main/java/com/example/vetlink/activity/SignupActivity.kt, app/src/main/java/com/example/vetlink/data/network/PetApi.kt, app/src/main/java/com/example/vetlink/fragment/PetDetailsFragment.kt, app/src/main/java/com/example/vetlink/repository/PetRepository.kt, app/src/main/java/com/example/vetlink/viewModel/MenuActivityViewModel.kt
=> kevin, features/add-pet

app/src/main/java/com/example/vetlink/fragment/MyPetsFragment.kt, app/src/main/java/com/example/vetlink/fragment/PetDetailsFragment.kt
fix reload data setelah ditambahkan
=> kevin, hotfix/reload-after-add-pet

app/src/main/java/com/example/vetlink/activity/MenuActivity.kt, app/src/main/java/com/example/vetlink/data/model/pets/PetBasic.kt, app/src/main/java/com/example/vetlink/data/model/queue/QueueDetail.kt, app/src/main/java/com/example/vetlink/data/model/queue/QueuesResponse.kt, app/src/main/java/com/example/vetlink/data/model/user/UserBasic.kt, app/src/main/java/com/example/vetlink/data/model/veteriner/VeterinerBasic.kt, app/src/main/java/com/example/vetlink/data/network/QueueApi.kt, app/src/main/java/com/example/vetlink/fragment/ScheduleFragment.kt, app/src/main/java/com/example/vetlink/repository/QueueRepository.kt
implementasi halaman histori antrian
=> kevin, features/get-queue

app/src/main/java/com/example/vetlink/adapter/ForumPageAdapter.kt, app/src/main/java/com/example/vetlink/adapter/ForumPostList.kt, app/src/main/java/com/example/vetlink/adapter/ForumPostListAdapter.kt, app/src/main/java/com/example/vetlink/data/model/comment/Comment.kt, app/src/main/java/com/example/vetlink/data/model/forums/Forum.kt, app/src/main/java/com/example/vetlink/data/model/user/UserBasic.kt, app/src/main/java/com/example/vetlink/data/network/response/queue/ResponseForums.kt, app/src/main/java/com/example/vetlink/fragment/ForumFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPrivateFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPublicFragment.kt, app/src/main/res/layout/each_item_forum_post.xml
=> kevin, features/customer-get-forums

app/src/main/java/com/example/vetlink/adapter/CommentListAdapter.kt, app/src/main/java/com/example/vetlink/adapter/ForumPostList.kt, app/src/main/java/com/example/vetlink/adapter/ForumPostListAdapter.kt, app/src/main/java/com/example/vetlink/data/model/comment/Comment.kt, app/src/main/java/com/example/vetlink/data/model/forums/Forum.kt, app/src/main/java/com/example/vetlink/fragment/ForumPrivateFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPublicFragment.kt, app/src/main/res/layout/each_item_row_comment.xml, app/src/main/res/layout/layout_bottom_sheet_comment_dialog.xml
implementasi halaman forum. forum dengan komentar
=> kevin, features/forums-comments

app/src/main/java/com/example/vetlink/fragment/ForumFragment.kt
=> kevin, features/reload-data-forum-after-add

app/src/main/java/com/example/vetlink/data/model/forums/ForumUpdateResponse.kt, app/src/main/java/com/example/vetlink/data/network/ForumApi.kt, app/src/main/java/com/example/vetlink/fragment/ForumPrivateFragment.kt, app/src/main/java/com/example/vetlink/repository/ForumRepository.kt, app/src/main/java/com/example/vetlink/viewModel/MainActivityViewModel.kt
implementasi fitur edit status forum
=> kevin, features/update-forum

app/src/main/java/com/example/vetlink/adapter/ForumPostList.kt, app/src/main/java/com/example/vetlink/data/model/forums/CommentAddResponse.kt, app/src/main/java/com/example/vetlink/data/model/forums/CommentsResponse.kt, app/src/main/java/com/example/vetlink/data/model/forums/Forum.kt, app/src/main/java/com/example/vetlink/data/network/ForumApi.kt, app/src/main/java/com/example/vetlink/fragment/ForumFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPrivateFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPublicFragment.kt, app/src/main/java/com/example/vetlink/repository/ForumRepository.kt, app/src/main/java/com/example/vetlink/viewModel/MainActivityViewModel.kt
implementasi fitur get forum tidak dengan comment dan fitur tambah komentar pada forum public
=> kevin, features/read-forum-comment-and-add-forum-public-comment

app/src/main/java/com/example/vetlink/fragment/ForumPrivateFragment.kt
memperbaiki tombol untuk merubah status forum
=> kevin, bugfix/forums-mark-as-found

app/src/main/java/com/example/vetlink/adapter/ForumPageAdapter.kt, app/src/main/java/com/example/vetlink/fragment/ForumFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPrivateFragment.kt, app/src/main/java/com/example/vetlink/fragment/ForumPublicFragment.kt
implementasi fitur komentar pada forum pribadi
=> kevin, features/private-forum-comment

app/src/main/java/com/example/vetlink/fragment/HomeFragment.kt
memperbaiki photo profile forum pada homefragment
=> kevin, hotfix/fix-user-forum-photo

app/src/main/java/com/example/vetlink/adapter/ForumPostListAdapter.kt
memperbaiki image update pada halaman forum
=> kevin, hotfix/fix-forum-image-update

app/src/main/java/com/example/vetlink/fragment/ClinicFragment.kt, app/src/main/java/com/example/vetlink/fragment/PetDetailsFragment.kt
implementasi fitur reset tipe hewan dengan ras hewan
=> kevin, features/reset-pet-breed

app/src/main/java/com/example/vetlink/activity/LoginActivity.kt, app/src/main/java/com/example/vetlink/viewModel/LoginActivityViewModel.kt
fitur menolak role selain customer pada saat login
=> kevin, features/reject-other-role
